services:
  minio:  
    container_name: dev-minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: stargate
    ports:
      - "9005:9000"
      - "9995:9001"
    volumes:
      - "/Users/praveenallam/Desktop/files-backend/data/minio-data:/data"


volumes:
 minio-data: 