[project]
name = "files-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.14",
    "minio>=7.2.15",
    "openai>=1.93.0",
    "redis>=6.2.0",
]
